In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [3]:
token = Tokenizer()

In [4]:
file_path = r"D:\Revision\Projects\Next_Word_Predictor\next_word_prediction_10000_lines.txt"

with open(file_path, "r", encoding="utf-8") as f:
    data = f.read()

print(data[:500])


The application generates context information at inference time.
The user optimizes training samples using deep learning.
The transformer learns natural language in real time.
The program generates language patterns for better results.
The dataset predicts sentence structure based on context.
The user evaluates language patterns based on context.
The system predicts sentence structure using deep learning.
The application evaluates input data with neural networks.
The system predicts context info


In [5]:
token.fit_on_texts([data])

In [6]:
token.word_index

{'the': 1,
 'language': 2,
 'in': 3,
 'time': 4,
 'model': 5,
 'user': 6,
 'context': 7,
 'with': 8,
 'training': 9,
 'for': 10,
 'real': 11,
 'program': 12,
 'predicts': 13,
 'evaluates': 14,
 'next': 15,
 'word': 16,
 'using': 17,
 'deep': 18,
 'learning': 19,
 'learns': 20,
 'optimizes': 21,
 'queries': 22,
 'information': 23,
 'text': 24,
 'sequences': 25,
 'application': 26,
 'natural': 27,
 'improves': 28,
 'during': 29,
 'modern': 30,
 'nlp': 31,
 'systems': 32,
 'system': 33,
 'architecture': 34,
 'network': 35,
 'previous': 36,
 'tokens': 37,
 'patterns': 38,
 'based': 39,
 'on': 40,
 'understands': 41,
 'at': 42,
 'inference': 43,
 'high': 44,
 'accuracy': 45,
 'input': 46,
 'data': 47,
 'modeling': 48,
 'neural': 49,
 'networks': 50,
 'analyzes': 51,
 'processes': 52,
 'handles': 53,
 'generates': 54,
 'algorithm': 55,
 'sentence': 56,
 'structure': 57,
 'transformer': 58,
 'dataset': 59,
 'better': 60,
 'results': 61,
 'samples': 62}

In [7]:
sequence = []
for sentence in data.split('\n'):
    print(sentence)
    tokenized_sentence = token.texts_to_sequences([sentence])[0]
    print(tokenized_sentence)
    for i in range(1,len(tokenized_sentence)):
        sequence.append(tokenized_sentence[:i+1])

The application generates context information at inference time.
[1, 26, 54, 7, 23, 42, 43, 4]
The user optimizes training samples using deep learning.
[1, 6, 21, 9, 62, 17, 18, 19]
The transformer learns natural language in real time.
[1, 58, 20, 27, 2, 3, 11, 4]
The program generates language patterns for better results.
[1, 12, 54, 2, 38, 10, 60, 61]
The dataset predicts sentence structure based on context.
[1, 59, 13, 56, 57, 39, 40, 7]
The user evaluates language patterns based on context.
[1, 6, 14, 2, 38, 39, 40, 7]
The system predicts sentence structure using deep learning.
[1, 33, 13, 56, 57, 17, 18, 19]
The application evaluates input data with neural networks.
[1, 26, 14, 46, 47, 8, 49, 50]
The system predicts context information with neural networks.
[1, 33, 13, 7, 23, 8, 49, 50]
The network processes text sequences for language modeling.
[1, 35, 52, 24, 25, 10, 2, 48]
The dataset improves sentence structure using deep learning.
[1, 59, 28, 56, 57, 17, 18, 19]
The algorithm

In [8]:
# sequence = []
# for i in range(1,len(tokenized_sentence)):
#     sequence.append(tokenized_sentence[:i+1])

In [9]:
sequence

[[1, 26],
 [1, 26, 54],
 [1, 26, 54, 7],
 [1, 26, 54, 7, 23],
 [1, 26, 54, 7, 23, 42],
 [1, 26, 54, 7, 23, 42, 43],
 [1, 26, 54, 7, 23, 42, 43, 4],
 [1, 6],
 [1, 6, 21],
 [1, 6, 21, 9],
 [1, 6, 21, 9, 62],
 [1, 6, 21, 9, 62, 17],
 [1, 6, 21, 9, 62, 17, 18],
 [1, 6, 21, 9, 62, 17, 18, 19],
 [1, 58],
 [1, 58, 20],
 [1, 58, 20, 27],
 [1, 58, 20, 27, 2],
 [1, 58, 20, 27, 2, 3],
 [1, 58, 20, 27, 2, 3, 11],
 [1, 58, 20, 27, 2, 3, 11, 4],
 [1, 12],
 [1, 12, 54],
 [1, 12, 54, 2],
 [1, 12, 54, 2, 38],
 [1, 12, 54, 2, 38, 10],
 [1, 12, 54, 2, 38, 10, 60],
 [1, 12, 54, 2, 38, 10, 60, 61],
 [1, 59],
 [1, 59, 13],
 [1, 59, 13, 56],
 [1, 59, 13, 56, 57],
 [1, 59, 13, 56, 57, 39],
 [1, 59, 13, 56, 57, 39, 40],
 [1, 59, 13, 56, 57, 39, 40, 7],
 [1, 6],
 [1, 6, 14],
 [1, 6, 14, 2],
 [1, 6, 14, 2, 38],
 [1, 6, 14, 2, 38, 39],
 [1, 6, 14, 2, 38, 39, 40],
 [1, 6, 14, 2, 38, 39, 40, 7],
 [1, 33],
 [1, 33, 13],
 [1, 33, 13, 56],
 [1, 33, 13, 56, 57],
 [1, 33, 13, 56, 57, 17],
 [1, 33, 13, 56, 57, 17, 18],
 

In [10]:
max_len = max([len(x) for x in sequence])
print(max_len)

11


In [11]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
pre_padded_sequence = pad_sequences(sequence, maxlen = max_len, padding = 'pre')
pre_padded_sequence

array([[ 0,  0,  0, ...,  0,  1, 26],
       [ 0,  0,  0, ...,  1, 26, 54],
       [ 0,  0,  0, ..., 26, 54,  7],
       ...,
       [ 0,  0,  0, ...,  9, 62, 10],
       [ 0,  0,  0, ..., 62, 10, 60],
       [ 0,  0,  0, ..., 10, 60, 61]], shape=(72037, 11), dtype=int32)

In [12]:
X = pre_padded_sequence[:,:-1]
X

array([[ 0,  0,  0, ...,  0,  0,  1],
       [ 0,  0,  0, ...,  0,  1, 26],
       [ 0,  0,  0, ...,  1, 26, 54],
       ...,
       [ 0,  0,  0, ..., 53,  9, 62],
       [ 0,  0,  0, ...,  9, 62, 10],
       [ 0,  0,  0, ..., 62, 10, 60]], shape=(72037, 10), dtype=int32)

In [13]:
y = pre_padded_sequence[:,-1]
y

array([26, 54,  7, ..., 10, 60, 61], shape=(72037,), dtype=int32)

In [14]:
len(token.word_index)

62

In [15]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes = 63)

In [16]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], shape=(72037, 63))

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [18]:
model = Sequential()
model.add(Embedding(63, 100, input_length=11))
model.add(LSTM(150))
model.add(Dense(63, activation='softmax'))

c:\Users\ROHIT VIRDI\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [19]:
model.compile(loss = 'categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [20]:
model.build(input_shape=(None, 11))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 11, 100)        │         6,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 63)             │         9,513 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 166,413 (650.05 KB)

 Trainable params: 166,413 (650.05 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.fit(X,y, epochs=150) 

Epoch 1/150
2252/2252 ━━━━━━━━━━━━━━━━━━━━ 32s 13ms/step - accuracy: 0.4574 - loss: 1.4950
Epoch 2/150
2252/2252 ━━━━━━━━━━━━━━━━━━━━ 26s 11ms/step - accuracy: 0.4837 - loss: 1.3005
Epoch 3/150
2252/2252 ━━━━━━━━━━━━━━━━━━━━ 25s 11ms/step - accuracy: 0.4857 - loss: 1.2961
Epoch 4/150
2252/2252 ━━━━━━━━━━━━━━━━━━━━ 21s 9ms/step - accuracy: 0.4879 - loss: 1.2935
Epoch 5/150
2252/2252 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - accuracy: 0.4854 - loss: 1.2924
Epoch 6/150
2252/2252 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.4857 - loss: 1.2904
Epoch 7/150
2252/2252 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.4872 - loss: 1.2900
Epoch 8/150
2252/2252 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - accuracy: 0.4866 - loss: 1.2895
Epoch 9/150
2252/2252 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - accuracy: 0.4853 - loss: 1.2884
Epoch 10/150
2252/2252 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - accuracy: 0.4863 - loss: 1.2881
Epoch 11/150
2252/2252 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - accuracy: 0.4889 - loss: 1.2865
Epoch

In [35]:
import numpy as np

In [44]:
words = "The user evaluates language"

for i in range(3):

    token_word = token.texts_to_sequences([words])[0]

    padded_token_word = pad_sequences([token_word], maxlen = 11, padding='pre')
    # print(padded_token_word)

    # model.predict(padded_token_word) #.shape
    # np.argmax(model.predict(padded_token_word))
    pos = np.argmax(model.predict(padded_token_word))

    for text,index in token.word_index.items():
        if  index == pos:
            print(text)

            text = text + " " + text
            print(text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
patterns
patterns patterns
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
patterns
patterns patterns
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
patterns
patterns patterns


In [37]:
token.word_index

{'the': 1,
 'language': 2,
 'in': 3,
 'time': 4,
 'model': 5,
 'user': 6,
 'context': 7,
 'with': 8,
 'training': 9,
 'for': 10,
 'real': 11,
 'program': 12,
 'predicts': 13,
 'evaluates': 14,
 'next': 15,
 'word': 16,
 'using': 17,
 'deep': 18,
 'learning': 19,
 'learns': 20,
 'optimizes': 21,
 'queries': 22,
 'information': 23,
 'text': 24,
 'sequences': 25,
 'application': 26,
 'natural': 27,
 'improves': 28,
 'during': 29,
 'modern': 30,
 'nlp': 31,
 'systems': 32,
 'system': 33,
 'architecture': 34,
 'network': 35,
 'previous': 36,
 'tokens': 37,
 'patterns': 38,
 'based': 39,
 'on': 40,
 'understands': 41,
 'at': 42,
 'inference': 43,
 'high': 44,
 'accuracy': 45,
 'input': 46,
 'data': 47,
 'modeling': 48,
 'neural': 49,
 'networks': 50,
 'analyzes': 51,
 'processes': 52,
 'handles': 53,
 'generates': 54,
 'algorithm': 55,
 'sentence': 56,
 'structure': 57,
 'transformer': 58,
 'dataset': 59,
 'better': 60,
 'results': 61,
 'samples': 62}

In [ ]:
import pickle

# Save the Keras model
model.save("next_word_model.h5")

# Save the Tokenizer object
with open('tokenizer.pkl', 'wb') as handle:
    pickle.dump(token, handle, protocol=pickle.HIGHEST_PROTOCOL)

# Save the max_len for use in the Streamlit app
with open('max_len.txt', 'w') as f:
    f.write(str(max_len))

print("Model, Tokenizer, and max_len saved successfully.")

Model, Tokenizer, and max_len saved successfully.
